import 'dart:math' as math;

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/svg.dart';
import 'package:injectable/injectable.dart';
import 'package:mazaya/src/config/language/locale_keys.g.dart';
import 'package:mazaya/src/config/res/assets.gen.dart';
import 'package:mazaya/src/config/res/config_imports.dart';
import 'package:mazaya/src/core/base_crud/code/domain/base_domain_imports.dart';
import 'package:mazaya/src/core/base_crud/code/presentation/cubit/base_cubit/async_cubit.dart';
import 'package:mazaya/src/core/extensions/base_state.dart';
import 'package:mazaya/src/core/extensions/context_extension.dart';
import 'package:mazaya/src/core/extensions/text_style_extensions.dart';
import 'package:mazaya/src/core/extensions/widgets/padding_extension.dart';
import 'package:mazaya/src/core/extensions/widgets/sized_box_helper.dart';
import 'package:mazaya/src/core/extensions/widgets/widget_extension.dart';
import 'package:mazaya/src/core/helpers/helpers.dart';
import 'package:mazaya/src/core/navigation/navigator.dart';
import 'package:mazaya/src/core/network/api_endpoints.dart';
import 'package:mazaya/src/core/shared/cubits/user_cubit/user_cubit.dart';
import 'package:mazaya/src/core/shared/models/base_model.dart';
import 'package:mazaya/src/core/widgets/badge_icon_widget.dart' show BadgeIconWidget;
import 'package:mazaya/src/core/widgets/buttons/loading_button.dart';
import 'package:mazaya/src/core/widgets/custom_messages.dart';
import 'package:mazaya/src/core/widgets/dialogs/visitor_pop_up.dart';
import 'package:mazaya/src/core/widgets/image_widgets/cached_image.dart';
import 'package:mazaya/src/core/widgets/pickers/default_bottom_sheet.dart';
import 'package:mazaya/src/core/widgets/universal_media/widgets.dart';
import 'package:mazaya/src/features/notifications/presentation/cubits/unread_notification_count_cubit.dart';
import 'package:mazaya/src/features/notifications/presentation/imports/view_imports.dart';
import 'package:mazaya/src/features/settings/presentation/imports/view_imports.dart';
import 'package:mazaya/src/features/more/entity/more_menu_item_entity.dart';

export '../view/more_tab_view.dart';
export '../widgets/more_tab_body.dart';
export '../widgets/more_section_widget.dart';

part '../cubits/log_out_cubit.dart';
part '../widgets/dialogs/log_out_dialog.dart';
part '../widgets/more_menu_card_widget.dart';
part '../widgets/profile_info_with_icons_widget.dart';