import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:mazaya/src/config/language/locale_keys.g.dart';
import 'package:mazaya/src/config/res/config_imports.dart';
import 'package:mazaya/src/core/base_crud/code/domain/base_domain_imports.dart';
import 'package:mazaya/src/core/base_crud/code/presentation/cubit/base_cubit/async_cubit.dart';
import 'package:mazaya/src/core/extensions/widgets/padding_extension.dart';
import 'package:mazaya/src/core/helpers/validators.dart';
import 'package:mazaya/src/core/navigation/navigator.dart';
import 'package:mazaya/src/core/network/api_endpoints.dart';
import 'package:mazaya/src/core/shared/cubits/user_cubit/user_cubit.dart';
import 'package:mazaya/src/core/shared/models/base_model.dart';
import 'package:mazaya/src/core/widgets/buttons/loading_button.dart';
import 'package:mazaya/src/core/widgets/dialogs/success_dialog.dart';
import 'package:mazaya/src/core/widgets/fields/text_fields/custom_text_field.dart';
import 'package:mazaya/src/core/widgets/scaffolds/default_scaffold.dart'
    show DefaultScaffold;
import 'package:mazaya/src/features/contact_us/entity/contact_us_params.dart';

part '../view/contact_us_view.dart';
part '../widgets/contact_us_body.dart';
part '../cubits/contact_us_cubit.dart';
