import 'package:mazaya/src/core/navigation/constants/imports_constants.dart';
import 'package:mazaya/src/core/navigation/helper/interfaces/helper_imports.dart';
import 'factory/transition_creator.dart';
import 'implementation/cupertino/options/cupertino_animation_option.dart';
import 'implementation/cupertino/cupertino_transition_animation.dart';
import 'implementation/fade/options/fade_animation_option.dart';
import 'implementation/fade/fade_transition_animation.dart';
import 'implementation/rotation/options/rotation_animation_option.dart';
import 'implementation/rotation/rotation_transition_animation.dart';
import 'implementation/scale/options/scale_animation_option.dart';
import 'implementation/scale/scale_transition_animation.dart';
import 'implementation/shake/options/shake_animation_options.dart';
import 'implementation/shake/shake_transition_animation.dart';
import 'implementation/size/options/size_animation_option.dart';
import 'implementation/size/size_transition_animation.dart';
import 'implementation/slide/options/slide_animation_option.dart';
import 'implementation/slide/slide_transition_animation.dart';

part 'transition_type_builder.dart';
